### PR TITLE
update README & add vendoring

### PR DESCRIPTION
**Pull request by err0r500**
I just cleaned up the README a little bit (mainly split the go installation and system the dependencies)

I also used [dep](https://github.com/golang/dep) to vendor the project

### CODE REVIEW

**Comment by err0r500** [comment]
Hi, Thanks to you for this great project !
I guess it should be fine now.
I removed the magicmime dependency and replaced it with [gabriel-vasile/mimetype](https://github.com/gabriel-vasile/mimetype) in order to remove a C dependency.
Tell me what you think about it

**Review by deiu — APPROVED** [review]
Good stuff!

**Comment by deiu** [comment]
It looks like I no longer have admin access for this repo, so you'll have to wait for (or ping) someone in the Solid team to merge it.

**Comment by err0r500** [comment]
Hahaha, ok, no problem.
I think I'll close these PRs and continue on my fork.
Thanks a lot !

**Comment by joe-mcnuggets** [comment]
@err0r500 I think it would be good if this PR will be merged, because I'll rewrite Dockerfile at my fork and will need dep too (:

**Comment by err0r500** [comment]
@joe-mcnuggets no problem, I won't touch this repo anymore ! :)
I pushed gold in [another repo of mine](https://github.com/err0r500/go-solid-server) to attempt a big refactoring since : 
1. I'm not sure it will be a succesful attempt :)
1. I can understand some may be unpleased by the changes I make 
1. I had to comment temporarily the server tests because they seemed to be based on mutations that were difficult to reproduce
1. Anyway, moving all the stuff back to the original gold repository may not be too difficult if the original maintainers are interested in.

**Comment by deiu** [comment]
I can't seem to find a way to manually trigger a build on Travis for this PR. @err0r500 can you please push a quick change to see if it auto-triggers a build?

**Comment by err0r500** [comment]
hmmm, maybe a dep ensure would fix the problem

**Comment by deiu** [comment]
Any thoughts on why the tests fail?

**Comment by err0r500** [comment]
Hi! 
TestFakeSMTPSecureDial() is failing in travis (works fine on my machine) so it may be env related

**Pull request merged**
